spring.application.name=myapp

# DB Properties
spring.datasource.url= jdbc:mysql://localhost:3306/hex_ticket_res_db?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password= 1234

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update

#Security props
jwt.secret=secret